### ISSUE TITLE
New Provider: Azure

### ISSUE THREAD

**Issue by lohman** [checkly/jamstack-deploy#24]
Hi ho,
Would love to see Azure on jamstackdeploy.com.

Reference Architecture:  https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/app-service-web-app/basic-web-app?tabs=cli

**Comment by ianaya89** [comment]
Hi @lohman, I will also take a look into that. We are already measuring [Azure static sites](https://azure.microsoft.com/en-us/services/app-service/static/). Is this something different? 

Thanks!

**Comment by lohman** [comment]
Oh...what the...I swear I didn't see Azure on the site before.  But now when I check from another computer, it's there.  So maybe I just plead temporary insanity.  Yeah I didn't think you had Static Sites on there but now I see it so I'll close this one.  Thanks for the response.
