### ISSUE TITLE
New provider for jamstackdeploy monitoring - Gatsby Cloud status monitoring

### ISSUE THREAD

**Issue by b2storefront** [checkly/jamstack-deploy#39]
### What problem does this feature solve?

Monitoring of the Gatsby Cloud Delivery Network 

### How would you implement this feature?

I would setup RUM pings from Checkly to some Gatsby Cloud hosted websites and build a dashboard

**Comment by ianaya89** [comment]
@b2storefront, thanks for your request. I will try to tackle both providers in the following weeks.

**Comment by ianaya89** [comment]
Hi @b2storefront, I was looking at Gatsby Cloud Delivery Network and its exclusive to Gatsby projects. Sadly it's out of the scope of this project because we want to measure generic JAMStack providers
