### ISSUE TITLE
Addining a new provider

### ISSUE THREAD

**Issue by alena-ko** [checkly/jamstack-deploy#5]
I'd love to see [Hostman](https://hostman.com/blog) on the [list of cloud hosting providers](https://www.jamstackdeploy.com/). It'd be interesting for me and other users to compare it to DO or Render, for example. Please let me know if you need some additional info from me. 
Thank you in advance

**Comment by ianaya89** [comment]
@alena-ko looks great. Didn't know about this provider. Will be working on this next week.

Thanks!

**Comment by ianaya89** [comment]
@alena-ko already implemented :)

**Comment by alena-ko** [comment]
Thank you! It's great to work with you:)

ср, 21 июл. 2021 г. в 05:17, Nacho Anaya ***@***.***>:
